$kind: http-example
name: Account password configured successfully. User must manually login.
request:
  url: "{{baseUrl}}/auth/register/complete"
  method: POST
  headers:
    Content-Type: application/json
    Accept: application/json
  body:
    type: json
    content: |-
      {
        "email": "<string>",
        "code": "<string>",
        "password": "<string>",
        "confirmPassword": "<string>",
        "tenantName": "<string>"
      }
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: text
    content: ""
order: 1000
