$kind: http-example
request:
  url: "{{baseUrl}}/roles/:id/permissions"
  method: POST
  headers:
    Content-Type: application/json
  pathVariables:
    - key: id
      value: <string>
      description: "(Required) "
  body:
    type: json
    content: |-
      {
        "permissionIds": [
          "<string>",
          "<string>"
        ]
      }
response:
  statusCode: 404
  statusText: Not Found
  body:
    type: text
    content: ""
order: 4000
