$kind: http-example
request:
  url: "{{baseUrl}}/global-config"
  method: POST
  headers:
    Content-Type: application/json
  body:
    type: json
    content: ""
response:
  statusCode: 409
  statusText: Conflict
  body:
    type: text
    content: ""
order: 2000
