$kind: http-example
request:
  url: "{{baseUrl}}/roles/:id/users"
  method: DELETE
  headers:
    Content-Type: application/json
  pathVariables:
    - key: id
      value: <string>
      description: "(Required) "
  body:
    type: json
    content: |-
      {
        "userIds": [
          "<string>",
          "<string>"
        ]
      }
response:
  statusCode: 404
  statusText: Not Found
  body:
    type: text
    content: ""
order: 3000
